// Listes d'articles partagées entre le suivi hebdomadaire, le suivi matériel
// et les autocontrôles (fiche perte/casse).

export const MATERIEL_ARTICLES: { name: string; defaultQty: number }[] = [
  { name: "Verre personnel", defaultQty: 3 },
  { name: "Verre à jus 22cl", defaultQty: 12 },
  { name: "Verre à thé", defaultQty: 66 },
  { name: "Verre à jus 33 cl", defaultQty: 48 },
  { name: "Verre à café", defaultQty: 36 },
  { name: "Verre macédoine", defaultQty: 0 },
  { name: "Grand verre", defaultQty: 22 },
  { name: "Coupe inox", defaultQty: 5 },
  { name: "Tasse café noir", defaultQty: 255 },
  { name: "Tasse café crème", defaultQty: 71 },
  { name: "Thiere en inox", defaultQty: 2 },
  { name: "Sous T.C.noir", defaultQty: 19 },
  { name: "Sous T.C.crème", defaultQty: 55 },
  { name: "Sous verre café noir", defaultQty: 66 },
  { name: "Assiette sous coupe", defaultQty: 4 },
  { name: "Assiette tulipe", defaultQty: 0 },
  { name: "Assiette crêpe", defaultQty: 20 },
  { name: "Cuillère C.Noir", defaultQty: 66 },
  { name: "Cuillère C. Crème", defaultQty: 96 },
  { name: "Cuillère Jus panaché", defaultQty: 54 },
  { name: "Cuillère à glace", defaultQty: 96 },
  { name: "Couteaux inox", defaultQty: 130 },
  { name: "Fourchette", defaultQty: 0 },
  { name: "Plateaux", defaultQty: 8 },
  { name: "Theire", defaultQty: 153 },
  { name: "CVC Theire", defaultQty: 153 },
  { name: "Cendrier rond", defaultQty: 18 },
  { name: "Pince à glace", defaultQty: 0 },
  { name: "Palette à Glace", defaultQty: 0 },
  { name: "CVC cendrier rond", defaultQty: 18 },
  { name: "Bec siphon", defaultQty: 0 },
  { name: "Porte addition", defaultQty: 0 },
  { name: "Jarra grand modèle", defaultQty: 98 },
  { name: "Jarra petit modèle", defaultQty: 0 },
  { name: "Presse agrume", defaultQty: 1 },
  { name: "Boite en plastique G", defaultQty: 0 },
  { name: "Boite en plastique P", defaultQty: 0 },
  { name: "Carafe", defaultQty: 0 },
  { name: "Spatule en inox", defaultQty: 8 },
  { name: "Spatule en plastique", defaultQty: 0 },
  { name: "Couteaux Légume", defaultQty: 21 },
  { name: "Couteaux G", defaultQty: 0 },
  { name: "Siphon", defaultQty: 0 },
  { name: "Moule Cornet", defaultQty: 2 },
  { name: "Moule Tulipe", defaultQty: 0 },
  { name: "Scoupe Topping", defaultQty: 0 },
  { name: "Moule 1L", defaultQty: 0 },
  { name: "Moule 0.5L", defaultQty: 0 },
  { name: "BIBERONS", defaultQty: 0 },
  { name: "SUPPORT TRANCHES", defaultQty: 0 },
  { name: "PLANCHES TRANCHES", defaultQty: 0 },
  { name: "PIQUE TICKET", defaultQty: 0 },
  { name: "PRESENTOIRE SERVIETTE", defaultQty: 0 },
  { name: "PORTE ADDITION", defaultQty: 0 },
  { name: "BROSSR VERRE", defaultQty: 0 },
  { name: "LAVETTE MICROFIBRES(JAUNE/VERTE/BLEU/ROUGE)", defaultQty: 0 },
  { name: "BROSSE SIPHON", defaultQty: 0 },
  { name: "BROSSE AGRUME", defaultQty: 0 },
  { name: "BROSSE METALLIQUE MACHINE A CORNET", defaultQty: 0 },
  { name: "ABRASIFS", defaultQty: 0 },
  { name: "Raclette", defaultQty: 0 },
  { name: "BALAI", defaultQty: 0 },
];

export const WEEKLY_TARTE_ARTICLES = [
  "Tarte 6", "Tarte 8", "Tarte 10", "Tte Sp.", "Tte.Sp 8", "Tte Mac.", "Tte Sor.",
  "Tche Sor.", "Tche Mac.", "Tche Nap.", "Bûche", "Bûche Sp.", "N.F", "Demis",
  "Maria Louisa", "Maria mangue", "Maria framboise", "Maria reglisse", "M.Loulou", "Panachés",
  "Mac.Chocolat P", "Mac.Pistache P", "Mac.Caramel P", "Mac.Cfé P", "Mac.Mng P", "Mac.Cit P",
  "Mac.Chocolat N", "Mac.Pistache N", "Mac.Caramel N", "Mac.Cfé N", "Mac.Mng N", "Mac.Cit N",
  "Chantilly,F,C", "Cho.Logo", "PJA", "Cho.Blnc", "Amd.Crml", "Sirop.Blc", "Sirop.Crml",
  "Merg.trt", "Merg.Pt KG", "Merg.Pt SCH", "Merg.Glacé", "Org.Confit", "Biscuit",
  "Bigarreaux", "Cake Chocolat", "Cake.citron", "Pain Savoi", "Brownies.G", "Brownies.Top",
  "Amandes.Top", "Noix.Top", "Tulipes", "Cornet", "Gaufrette",
  "Orange fruits", "Citron fruits", "POMME fruits", "POIRE fruits", "Ananas fruits", "Kiwi fruits",
];
export const WEEKLY_NETTOYANT_ARTICLES = [
  "Rc 20", "Chlorane", "Solnet", "Flexi", "Mitard A", "Renovac", "Clean plack",
  "Handonet", "Rince Matic", "Wach Matic", "Handobac",
];
export const WEEKLY_GLACE_ARTICLES = [
  "Nougat", "Praliné", "Vanille", "Chocolat", "Pistache", "Caramel", "Moka",
  "Parfait", "Fraise", "Framboise", "Orange", "Mangue", "Citron", "Pêche",
  "Banane", "Citron menthe", "Orange cannelle", "Réglisse",
  "Crème fraîche (mousse fouettée)",
];
export const WEEKLY_ALL_ARTICLES = [
  ...WEEKLY_TARTE_ARTICLES,
  ...WEEKLY_GLACE_ARTICLES,
  ...WEEKLY_NETTOYANT_ARTICLES,
];
